### ISSUE TITLE
a quastion

### ISSUE THREAD

**Issue by mostafaasadi** [xkollar/tor-openshift#5]
Hi 
It's not a issues , just a way to ask a quastion 
Is it possible with tor-openshift to config a relay private tor bridge on openshift servers ? 
best regard

**Comment by xkollar** [comment]
Hi (& sorry for the late reply).

OpenShifTor is designed to make your service accessible via Tor, not to access other other Tor services from/via you app. You may try to modify it, mostly tweaking `tor/etc/tor/torrc.erb`. However, I have to warn you that you might encounter issues (most notably being **banned**) in case you try running Tor proxy on public OpenShift instance (it is (or at least was) forbidden in their policy)... well, unless you get permission (which is not simple thing to get).

Thanks for the question and have a nice day :+1:.
